# Generated by Django 5.0.4 on 2024-04-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceSphere', '0003_service_available_service_category_service_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='date',
            new_name='date_time',
        ),
    ]
