# Generated by Django 5.0.4 on 2024-04-17 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceSphere', '0005_booking_confirmed_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
