# Generated by Django 5.0.4 on 2024-04-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceSphere', '0006_service_service_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
